- src/ui/edit_view/edit_view.vala
Check for valid url before opening.
Resolves #3
> Support ctl-click to open links.

- src/ui/window/app_menu/app_menu.blp
> Fix main menu button size.

- lib/notebook_icon_type.vala
- lib/provider.vala
- lib/trash.vala
- search-provider/search-provider.vala
- src/ui/edit_view/edit_view.vala
- src/ui/widgets/markdown/markdown_view.vala
- src/ui/window/notebooks_bar/notebook_create_popup.vala
- src/ui/window/window_model.vala
Last of the non deprecated warnings handled.
> Warning cleanups

- snap/snapcraft.yaml
Hi, as you requested. This is the separate PR for the manifest
> added snap manifest

- src/ui/window/notebooks_bar/notebooks_bar.blp
- src/ui/window/window.blp
> Display scroll bars for notebooks and notes list.

- lib/util/file_utils.vala
Like if the user moved it in the background for some reason.
Resolves #23
> Create a directory if it doesn't exist.

- src/ui/preferences/preferences.blp
- src/ui/preferences/preferences.vala
> Add option to set the fixed with size of the note area.

- data/app.gschema.xml
- src/ui/preferences/preferences.blp
- src/ui/preferences/preferences.vala
- src/ui/window/notebooks_bar/notebooks_bar.vala
- src/ui/window/window.vala
> Add option to always display the all notes notebook.

- src/ui/widgets/markdown/markdown_view.vala
> Add double backtick support.

- src/application.vala
- src/ui/window/window_model.vala
> When creating a new note, use any selected text for the note name

- data/app.gschema.xml
- lib/notebook/local_notebook.vala
- lib/provider.vala
- lib/trash.vala
- src/ui/preferences/preferences.blp
- src/ui/preferences/preferences.vala
> Add option to make the trash visible on the file system.

- lib/note.vala
- src/ui/window/window_model.vala
Include dialog boxes for what to do if there are changes in the current note.
> Monitor notes and reload if changed on disk.

- src/ui/widgets/markdown/markdown_view.vala
> Indent ordered/unordered lists.

- src/ui/edit_view/edit_view.vala
- src/ui/preferences/preferences.blp
- src/ui/preferences/preferences.vala
- src/ui/widgets/markdown/markdown_view.vala
Support font sizes in preferences and the notes.
> Font sizes

- data/app.gschema.xml
> Fix a typo

- src/application.vala
- src/ui/preferences/preferences.vala
> Replace deprecated export dialog

- lib/provider.vala
> Fix reversed alpha sort order.

- src/ui/edit_view/edit_view.vala
- src/ui/file_editor/file_editor_window.vala
- src/ui/popup/notebook_selection_popup/notebook_selection_popup.vala
- src/ui/window/notebooks_bar/notebooks_bar.vala
- src/ui/window/window.vala
and bring back file editor scroll headerbar behaviour.
> Switch to add/remove css class calls

- src/ui/window/window.vala
- src/ui/window/window_model.vala
as well as a minor formatting fix.
Resolves #92
> Fix the message in the edit window with an empty trash

- src/ui/edit_view/cheatsheet/markdown_cheatsheet.blp
- src/ui/edit_view/cheatsheet/markdown_cheatsheet.md
- src/ui/edit_view/cheatsheet/markdown_cheatsheet.vala
Fixes https://github.com/toolstack/Folio/issues/111
> Add title bar widget to markdown cheatsheet

- lib/provider.vala
> Fix deletion of notebooks.

- src/application.vala
> Check if a file is a uri instead of a path before giving up.

- src/ui/window/sidebar/note_card.vala
> Don't select rename text.

- src/ui/widgets/markdown/markdown_view.vala
> Skip formatting md styles when inside of a link.

- src/ui/edit_view/edit_view.vala
> Fix ctrl-scroll getting stuck sometimes.

- lib/note.vala
- src/application.vala
- src/ui/strings.vala
- src/ui/window/window.blp
- src/ui/window/window.vala
> Give option to open non md/text files in system handler.

- src/ui/edit_view/edit_view.vala
> Fix ctrl-click handling when the window loses focus

- lib/notebook_icon_type.vala
- lib/notebook_info.vala
- lib/provider.vala
- src/ui/widgets/notebook_icon/notebook_preview.vala
- src/ui/window/notebooks_bar/notebook_create_popup.blp
- src/ui/window/notebooks_bar/notebook_create_popup.vala
Aka support emojis and other text.
Resolves #107.
> Add custom text for icons in notebooks.

- data/app.gschema.xml
- src/ui/edit_view/edit_view.vala
- src/ui/preferences/preferences.blp
- src/ui/preferences/preferences.vala
- src/ui/strings.vala
- src/ui/widgets/markdown/markdown_view.vala
> Add option to set url detection level.

- lib/meson.build
- lib/notebook/local_notebook.vala
- lib/provider.vala
- lib/util/NaturalCollate.vala
- src/ui/preferences/preferences.vala
- src/ui/strings.vala
> Add natural sort option for notebooks/notes.

- lib/provider.vala
- lib/util/file_utils.vala
> Fix deleting notebooks when trash already has one with the same name

- lib/trash.vala
and still show up in the trash list.
> Allow trashed items to have zero size

- src/application.vala
- src/ui/window/window_model.vala
> Fix opening notes from the command line.

- po/LINGUAS
- po/nb.po
- src/application.vala
- src/ui/strings.vala
- src/ui/window/window.vala
This adds a Norwegian Bokmål translation to Folio.
(and fixes a small issue with the `F9` keyboard shortcut!)
> Add Norwegian Bokmål translation

- data/app.metainfo.xml.in
- src/application.vala
- src/ui/edit_view/edit_view.vala
- src/ui/widgets/markdown/markdown_view.vala
> Fix mono zooming

- data/app.gschema.xml
- src/ui/popup/notebook_selection_popup/notebook_list_item.vala
- src/ui/preferences/preferences.blp
- src/ui/preferences/preferences.vala
- src/ui/window/sidebar/note_card.vala
> Add long notebook/note name display support.

- src/css/style.css
> Add a default theme color

- src/application.vala
aka don't try and call a method on a null pointer.
> Avoid a crash

- src/ui/window/window.vala
that was accidentally deleted in #183.
Resolves #199
> Fix autosave

- lib/util/file_utils.vala
- src/application.vala
- src/ui/preferences/preferences.vala
Should, finally, resolve #112.
> Expand a tilde if it exists in our notes/trash directory.

- src/ui/window/notebooks_bar/notebook_create_popup.blp
> Increase the padding for newer widget

- src/ui/edit_view/edit_view.vala
> Handle the case when inserting an empty link tag

- data/app.metainfo.xml.in
> Update summary to match flathub standards.

- src/ui/window/app_menu/app_menu.blp
- src/ui/window/window.blp
> Add tooltips to the main/note menu.

- src/ui/widgets/markdown/markdown_view.vala
...and avoid multiple inserts/deletes.
> Fix unsaved state if setting line type via the toolbar

- po/ca.po
> Rename Catalan to correct code.

- src/ui/window/window.vala
> Avoid the sidebar being opened during a save.

- src/ui/window/window.vala
So users don't lose progress unexpectedly.
> window: Save note on exit

- src/ui/window/font_scale/font_scale.vala
> Bind to zoom buttons after we have the edit_view.

- com.toolstack.Folio.json
> Move to Gnome 48.

- src/ui/window/window_model.vala
...so when the trash is selected you can reselect your last notebook.
> Disable auto select on the notebook list

- lib/note.vala
- src/ui/window/window.vala
- src/ui/window/window_model.vala
> Fix save after rename.

- src/ui/widgets/markdown/markdown_view.vala
> Match lists with more than a single digit.
